print("Ingresa los parámetros del Enunciado 3 : \n")
print("-----------------------------------------\n")
texto    = input("Ingresa un campo texto                 :")
booleano = bool(input("Ingresa un campo booleano True o False :"))
entero   = int(input("Ingresa un Numero Entero               :"))
decimal  = float(input("Ingresa un Numero Float o Decimal      :"))
print ("El campo", texto, "es", type(texto))
print ("El campo", booleano, "es", type(booleano))
print ("El campo", entero, "es", type(entero))
print ("El campo", decimal, "es", type(decimal))
