# Operadores Aritmeticos
num_1 = int(input("Ingresa El Primer  Numero :"))
num_2 = int(input("Ingresa El Segundo Numero :"))
print ("\nLa Suma Es ",num_1+num_2)
print ("La Resta Es ",num_1-num_2)
print ("La Multiplicacion Es ",num_1*num_2)
print ("La Division Es ",num_1/num_2)
print ("La Division Entera Es ",num_1//num_2)
print ("El Resto Es ",num_1%num_2)
print ("La Potencia Es ",num_1**num_2)
